version: '2'
services:
  db:
    build: ./db/
    image: mwellner/voting-db
    ports:
    - "5555:5432"
  redis:
    image: redis:alpine
  result-app:
    build: ./result-python/
    image: mwellner/voting-result
    links:
    - "db"
    ports:
    - "5000"
  load-balancer:
    image: dockercloud/haproxy
    depends_on:
    - "result-app"
    ports: 
    - "8080:80"
    links:
    - "result-app"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  input-app:
    build: ./input-python/
    image: mwellner/voting-input-python
    ports:
    - "8090:5000"
    links:
    - "redis"
  worker:
    build: ./worker-nodejs/
    image: mwellner/voting-worker
    links:
    - "db"
    - "redis"
