version: '2'
services:
  db:
    build: ./db/
    image: mwellner/voting-db
    ports:
    - "5555:5432"
  redis:
    image: redis:alpine
    ports:
    - "8888:6379"
  result:
    build: ./result-python/
    image: mwellner/voting-result
    ports:
    - "8080:5000"
    links:
    - "db"
  input:
    build: ./input-python/
    image: mwellner/voting-input-python
    ports:
    - "8090:5000"
    links:
    - "redis"
  worker:
    build: ./worker-nodejs/
    image: mwellner/voting-worker1
    links:
    - "redis"
    - "db"
